import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { api } from "gametest/utils/api";

import "gametest/styles/globals.css";
import Head from "next/head";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <>
      <Head>
        <title>GameTest</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/IMG_0040.PNG" />
      </Head>
        <SessionProvider session={session}>
          <Component {...pageProps} />
        </SessionProvider>
    </>
  );
};

export default api.withTRPC(MyApp);
